### ISSUE TITLE
The proof of the initialization 

### ISSUE THREAD

**Issue by william-ljz** [WJ-Chang-42/IndoorPanoDepth#1]
The paper said: "The proof of the initialization is provided in the supplementary material.", but i I didn't find

**Comment by WJ-Chang-42** [comment]
The supplementary material is available at https://[openaccess.thecvf.com/content/CVPR2023/supplemental/Chang_Depth_Estimation_From_CVPR_2023_supplemental.pdf](https://openaccess.thecvf.com/content/CVPR2023/supplemental/Chang_Depth_Estimation_From_CVPR_2023_supplemental.pdf).
